/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kuharski' at '7/2/16 11:12 PM' with Gradle 2.13
 *
 * @author kuharski, @date 7/2/16 11:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
